FROM golang:1.26-bookworm

WORKDIR /app

COPY go.mod go.sum* ./
RUN [ -f go.sum ] && go mod download || true

RUN curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b /usr/local/bin

COPY . .

CMD ["air", "-c", ".air.toml"]
